// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFITR3mPiq4jGTAsO8LMKzr8SdAAmKvw',
    appId: '1:50679743569:web:e24aa6c069cba7a6c32470',
    messagingSenderId: '50679743569',
    projectId: 'universalgo-9a30d',
    authDomain: 'universalgo-9a30d.firebaseapp.com',
    storageBucket: 'universalgo-9a30d.firebasestorage.app',
    measurementId: 'G-Z31FSHNGK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1yNE57dtj5P4uSmE78mmW1IybDeIZC7I',
    appId: '1:50679743569:android:4b76492718567123c32470',
    messagingSenderId: '50679743569',
    projectId: 'universalgo-9a30d',
    storageBucket: 'universalgo-9a30d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWLhyelfeIYpdxraxY045zUMZurQccwzg',
    appId: '1:50679743569:ios:bd10fe9cf2f14764c32470',
    messagingSenderId: '50679743569',
    projectId: 'universalgo-9a30d',
    storageBucket: 'universalgo-9a30d.firebasestorage.app',
    iosBundleId: 'com.example.universalGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWLhyelfeIYpdxraxY045zUMZurQccwzg',
    appId: '1:50679743569:ios:bd10fe9cf2f14764c32470',
    messagingSenderId: '50679743569',
    projectId: 'universalgo-9a30d',
    storageBucket: 'universalgo-9a30d.firebasestorage.app',
    iosBundleId: 'com.example.universalGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqFITR3mPiq4jGTAsO8LMKzr8SdAAmKvw',
    appId: '1:50679743569:web:fb9661f6280e1fb8c32470',
    messagingSenderId: '50679743569',
    projectId: 'universalgo-9a30d',
    authDomain: 'universalgo-9a30d.firebaseapp.com',
    storageBucket: 'universalgo-9a30d.firebasestorage.app',
    measurementId: 'G-1MG0KWK0DD',
  );
}
